name: Test Actions
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  Test-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 12.16.2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
  Build-Project:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 12.16.2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build project
        run: npm run build
